services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/app/dockerfile.yaml
      target: production
    image: k8s-app-deployment:prod
    restart: unless-stopped
    env_file:
      - ormconfig.env
    ports:
      - "3000:3000"
    networks:
      - myapp-network

  mysql:
    image: mariadb:5.5
    restart: unless-stopped
    env_file:
      - dbconfig.env
    ports:
      - "3306:3306"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
