services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/app/dockerfile.yaml
      target: production
      args:
        VERSION: ${VERSION:-latest}
    image: vco7/k8s-app-deployment:${VERSION:-latest}
    restart: unless-stopped
    env_file:
      - k8s/app/secret.env
    ports:
      - "3000:3000"
    networks:
      - myapp-network
    depends_on:
      - mysql

  mysql:
    image: mariadb:5.5
    restart: unless-stopped
    env_file:
      - k8s/mysql/secret.env
    ports:
      - "3306:3306"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
