apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
