apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app
  namespace: k8s-app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: backend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app
