###   STAGE 1: Build the app

FROM node:24-alpine3.23 AS builder

WORKDIR /app

#   Install dependencies and snapshot them in the layer cache
COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

#   Compilation
COPY . .

RUN yarn tsc

RUN yarn install --frozen-lockfile --production \
    && yarn cache clean

###   STAGE 2: Run the app

FROM node:24-alpine3.23 AS production
WORKDIR /app

USER node

#   Copy runtime manifest
COPY --chown=node:node --from=builder /app/package.json ./

COPY --chown=node:node --from=builder /app/node_modules ./node_modules

#   Copy compiled code from the builder stage
COPY --chown=node:node --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/index.js"]
